### ISSUE TITLE
Unable to resolve AWS account to use

### ISSUE THREAD

**Issue by jleck** [localstack/aws-cdk-local#2]
Hi,

I noticed you released 1.65.0. I have been using 1.64.1-dev1 without issue. After upgrading, I'm now getting the following error when bootstrapping:

```
Unable to resolve AWS account to use. It must be either configured when you define your CDK or through the environment
```

When I deploy I get:

```
MarlonBrando-Localstack-Core failed: Error: Unable to resolve AWS account to use. It must be either configured when you define your CDK or through the environment
    at SdkProvider.resolveEnvironment (/home/jleckenby/Development/pimberly/marlon-brando-monorepo/node_modules/aws-cdk/lib/api/aws-auth/sdk-provider.ts:178:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at CloudFormationDeployments.prepareSdkFor (/home/jleckenby/Development/pimberly/marlon-brando-monorepo/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:212:33)
    at CloudFormationDeployments.deployStack (/home/jleckenby/Development/pimberly/marlon-brando-monorepo/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:149:70)
    at CdkToolkit.deploy (/home/jleckenby/Development/pimberly/marlon-brando-monorepo/node_modules/aws-cdk/lib/cdk-toolkit.ts:180:24)
    at initCommandLine (/home/jleckenby/Development/pimberly/marlon-brando-monorepo/node_modules/aws-cdk/bin/cdk.ts:197:9)
Unable to resolve AWS account to use. It must be either configured when you define your CDK or through the environment
```

Normal CDK bootstrap works fine.

**Comment by whummer** [comment]
Thanks for reporting @jleck . Can you please share some details about your LocalStack configuration? Specifically, is the STS service configured (`sts` added as part of the `SERVICES` variable)? Also, perhaps there is some cached data in `~/.cdk/cache` that needs to be cleaned up..?

**Comment by karin-jsq** [comment]
I also ran into this error, but found it was a docker networking issue for me.  I have a docker-compose.yml file, with a localstack service definition like this:
```
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=cloudformation,ec2,iam,lambda,rds,s3,secretsmanager,sqs
      - DEBUG=${DEBUG-True}
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-docker-reuse}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-west-2
    volumes:
      - "./build/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

and a custom service that has our cdk requirements and cdklocal installed
```
  dev-server:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    environment:
      LOCALSTACK_HOSTNAME: localstack
    volumes:
        - .:/usr/local/src
```

I found that i needed to have the above `LOCALSTACK_HOSTNAME` variable set to the name of my localstack service (in this case, called `localstack`).  Otherwise, i had docker networking related issues, since cdklocal defaults to looking for `http://localhost:4566` and my instance of localstack was instead hosted in the docker network as `http://localstack:4566`.

Other working alternatives (that were less viable for our usecase) included setting `network_mode: host` on both services, to allow them to "see" each other as localhost.

**Comment by jleck** [comment]
Hi @whummer 

Solved by adding STS to localstack. Not sure why the last version worked without it! However, I now run into https://github.com/localstack/aws-cdk-local/issues/1. Will track that bug, thanks! :)
