### ISSUE TITLE
Multi-account with LocalStack PRO and cdklocal does not honor the custom account ID

### ISSUE THREAD

**Issue by dominikschubert** [localstack/aws-cdk-local#74]
```bash
export AWS_ACCESS_KEY_ID=000000000001
export AWS_SECRET_ACCESS_KEY=test
export AWS_REGION=us-east-1

cdklocal bootstrap
```

Expected behavior: LocalStack creates an ECR repository in account `000000000001`
Actual behavior: LocalStack creates an ECR repository in account `000000000000`

**Comment by vincenthongzy** [comment]
@dominikschubert apologies for the ping, is this issue still being looked into?

**Comment by whummer** [comment]
@dominikschubert Just gave this a quick try with the latest version of LocalStack and `cdklocal` (using CDK version 2.62.2).

```
$ export AWS_ACCESS_KEY_ID=000000000001 AWS_SECRET_ACCESS_KEY=test AWS_REGION=us-east-1
$ cdklocal init app --language=python
...
$ pip install -r requirements.txt
...
$ cdklocal bootstrap
...
 ✅  Environment aws://000000000001/us-east-1 bootstrapped.
...
$ awslocal ecr describe-repositories | grep repositoryName
...
            "repositoryName": "cdk-hnb659fds-container-assets-000000000001-us-east-1",

```

Looks like this issue is potentially already solved in the meantime?

@vincenthongzy Are you able to replicate these results? Please note that for ECR to work fully end-to-end, you'll need a LocalStack Pro license (free trial available). Please keep us posed on how it goes.. Thanks!

**Comment by lakkeger** [comment]
Hi @vincenthongzy! We just wanted to follow up to see whether your issue has been resolved. Were you able to get it working with the latest version of LocalStack? We would appreciate your feedback!

**Comment by vincenthongzy** [comment]
Apologies for the late reply, but yes this does work with the latest version of `localstack-pro` and `aws-cdk-local` !

**Comment by lakkeger** [comment]
Thank you for your feedback. We are delighted it's working! If you experience any other issues, please do not hesitate to contact us.
